### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by notlucasdma** [AGG2017/ACK2-Webserver#1]
Is this project fail proof and is there any showcase how to set it up?

**Comment by AGG2017** [comment]
This project is only for advanced users that can read and modify C source code the way they want it to be. The rest of the users should use the compiled version available as an option in the customer firmware project. It is a very simple code that shouldn't be a problem for any advanced user. A daemon in the printer written on C can do anything, so the custom webserver can be very powerful and dangerous at the same time if improperly modified. Use it at your own risk. Nothing more than what is already included in this project is available.
